### ISSUE TITLE
no code

### ISSUE THREAD

**Issue by spiside** [kkilly41/GithubRresposition#1]
Hi! Great project.

I'm having trouble seeing any code. Can you help me out?

thanks

**Comment by MimmyJau** [comment]
i'm having trouble seeing it too

**Comment by kkilly41** [comment]
Hi fellow codesters!

Thanks for your interest in my project. You have commented against the intended configuration for this repository, so I have closed this issue.

Please let me know if you reach any other "aha!" moments during your review.

Happy coding!
K-Rock
